# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'spelang' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for spelang

  pod 'SnapKit'
  pod 'KeychainSwift'
  pod 'CombineExt'
  pod 'Kingfisher'
  pod 'Alamofire', '~> 5.2'
  pod 'GoogleMLKit/DigitalInkRecognition', '3.2.0'

end

post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      end
    end
end
